<?php
array(
    "AD"=>array("pt"=>"Andorra","es"=>"Andorra","en"=>"Andorra"),
    "AE"=>array("pt"=>"Emiratos Árabes Unidos","es"=>"Emiratos Árabes Unidos","en"=>"United Arab Emirates"),
    "AF"=>array("pt"=>"Afeganistão","es"=>"Afganistán","en"=>"Afghanistan"),
    "AG"=>array("pt"=>"Antígua e Barbuda","es"=>"Antigua y Barbuda","en"=>"Antigua and Barbuda"),
    "AI"=>array("pt"=>"Anguila","es"=>"Anguila","en"=>"Anguilla"),
    "AL"=>array("pt"=>"Albânia","es"=>"Albania","en"=>"Albania"),
    "AM"=>array("pt"=>"Arménia","es"=>"Armenia","en"=>"Armenia"),
    "AN"=>array("pt"=>"Antilhas Neerlandesas","es"=>"Antillas Neerlandesas","en"=>"Netherlands Antilles"),
    "AO"=>array("pt"=>"Angola","es"=>"Angola","en"=>"Angola"),
    "AQ"=>array("pt"=>"Antárctida","es"=>"Antártida","en"=>"Antarctica"),
    "AR"=>array("pt"=>"Argentina","es"=>"Argentina","en"=>"Argentina"),
    "AS"=>array("pt"=>"Samoa Americana","es"=>"Samoa Americana","en"=>"American Samoa"),
    "AT"=>array("pt"=>"Áustria","es"=>"Austria","en"=>"Austria"),
    "AU"=>array("pt"=>"Austrália","es"=>"Australia","en"=>"Australia"),
    "AW"=>array("pt"=>"Aruba","es"=>"Aruba","en"=>"Aruba"),
    "AX"=>array("pt"=>"ÅLAND ISLANDS","es"=>"ÅLAND ISLANDS","en"=>"ÅLAND ISLANDS"),
    "AZ"=>array("pt"=>"Azerbaijão","es"=>"Azerbaiyán","en"=>"Azerbaijan"),
    "BA"=>array("pt"=>"Bósnia e Herzegovina","es"=>"Bosnia y Hercegovina","en"=>"Bosnia and Herzegovina"),
    "BB"=>array("pt"=>"Barbados","es"=>"Barbados","en"=>"Barbados"),
    "BD"=>array("pt"=>"Bangladeche","es"=>"Bangladesh","en"=>"Bangladesh"),
    "BE"=>array("pt"=>"Bélgica","es"=>"Bélgica","en"=>"Belgium"),
    "BF"=>array("pt"=>"Burquina Faso","es"=>"Burkina Faso","en"=>"Burkina Faso"),
    "BG"=>array("pt"=>"Bulgária","es"=>"Bulgaria","en"=>"Bulgaria"),
    "BH"=>array("pt"=>"Barém","es"=>"Bahráin","en"=>"Bahrain"),
    "BI"=>array("pt"=>"Burúndi","es"=>"Burundi","en"=>"Burundi"),
    "BJ"=>array("pt"=>"Benim","es"=>"Benín","en"=>"Benin"),
    "BL"=>array("pt"=>"SAINT BARTHÉLEMY","es"=>"SAINT BARTHÉLEMY","en"=>"SAINT BARTHÉLEMY"),
    "BM"=>array("pt"=>"Bermudas","es"=>"Bermudas","en"=>"Bermuda"),
    "BN"=>array("pt"=>"Brunei","es"=>"Brunéi","en"=>"Brunei"),
    "BO"=>array("pt"=>"Bolívia","es"=>"Bolivia","en"=>"Bolivia"),
    "BR"=>array("pt"=>"Brasil","es"=>"Brasil","en"=>"Brazil"),
    "BS"=>array("pt"=>"Baamas","es"=>"Bahamas","en"=>"The Bahamas"),
    "BT"=>array("pt"=>"Butão","es"=>"Bután","en"=>"Bhutan"),
    "BV"=>array("pt"=>"Ilha Bouvet","es"=>"Isla Bouvet","en"=>"Bouvet Island"),
    "BW"=>array("pt"=>"Botsuana","es"=>"Botsuana","en"=>"Botswana"),
    "BY"=>array("pt"=>"Bielorrússia","es"=>"Bielorrusia","en"=>"Belarus"),
    "BZ"=>array("pt"=>"Belize","es"=>"Belice","en"=>"Belize"),
    "CA"=>array("pt"=>"Canadá","es"=>"Canadá","en"=>"Canada"),
    "CC"=>array("pt"=>"Ilhas dos Cocos","es"=>"Islas Cocos","en"=>"Cocos (Keeling) Islands"),
    "CD"=>array("pt"=>"Congo-Kinshasa","es"=>"República Democrática del Congo","en"=>"Democratic Republic of the Congo"),
    "CF"=>array("pt"=>"República Centro-Africana","es"=>"República Centroafricana","en"=>"Central African Republic"),
    "CG"=>array("pt"=>"Congo-Brazzaville","es"=>"Congo","en"=>"Congo"),
    "CH"=>array("pt"=>"Suíça","es"=>"Suiza","en"=>"Switzerland"),
    "CI"=>array("pt"=>"Costa do Marfim","es"=>"Costa de Marfil","en"=>"Côte d'Ivoire"),
    "CK"=>array("pt"=>"Ilhas Cook","es"=>"Islas Cook","en"=>"Cook Islands"),
    "CL"=>array("pt"=>"Chile","es"=>"Chile","en"=>"Chile"),
    "CM"=>array("pt"=>"Camarões","es"=>"Camerún","en"=>"Cameroon"),
    "CN"=>array("pt"=>"China","es"=>"China","en"=>"China"),
    "CO"=>array("pt"=>"Colômbia","es"=>"Colombia","en"=>"Colombia"),
    "CR"=>array("pt"=>"Costa Rica","es"=>"Costa Rica","en"=>"Costa Rica"),
    "CU"=>array("pt"=>"Cuba","es"=>"Cuba","en"=>"Cuba"),
    "CV"=>array("pt"=>"Cabo Verde","es"=>"Cabo Verde","en"=>"Cape Verde"),
    "CX"=>array("pt"=>"Ilha do Natal","es"=>"Isla Christmas","en"=>"Christmas Island"),
    "CY"=>array("pt"=>"Chipre","es"=>"Chipre","en"=>"Cyprus"),
    "CZ"=>array("pt"=>"República Checa","es"=>"República Checa; Chequia","en"=>"Czech Republic"),
    "DE"=>array("pt"=>"Alemanha","es"=>"Alemania","en"=>"Germany"),
    "DJ"=>array("pt"=>"Jibuti","es"=>"Yibuti","en"=>"Djibouti"),
    "DK"=>array("pt"=>"Dinamarca","es"=>"Dinamarca","en"=>"Denmark"),
    "DM"=>array("pt"=>"Domínica","es"=>"Dominica","en"=>"Dominica"),
    "DO"=>array("pt"=>"República Dominicana","es"=>"República Dominicana","en"=>"Dominican Republic"),
    "DZ"=>array("pt"=>"Argélia","es"=>"Argelia","en"=>"Algeria"),
    "EC"=>array("pt"=>"Equador","es"=>"Ecuador","en"=>"Ecuador"),
    "EE"=>array("pt"=>"Estónia","es"=>"Estonia","en"=>"Estonia"),
    "EG"=>array("pt"=>"Egipto","es"=>"Egipto","en"=>"Egypt"),
    "EH"=>array("pt"=>"Sara Ocidental","es"=>"Sáhara Occidental","en"=>"Western Sahara"),
    "ER"=>array("pt"=>"Eritreia","es"=>"Eritrea","en"=>"Eritrea"),
    "ES"=>array("pt"=>"Espanha","es"=>"España","en"=>"Spain"),
    "ET"=>array("pt"=>"Etiópia","es"=>"Etiopía","en"=>"Ethiopia"),
    "FI"=>array("pt"=>"Finlândia","es"=>"Finlandia","en"=>"Finland"),
    "FJ"=>array("pt"=>"Fiji","es"=>"Fiyi","en"=>"Fiji"),
    "FK"=>array("pt"=>"Ilhas Falkland","es"=>"Islas Malvinas","en"=>"Falkland Islands"),
    "FM"=>array("pt"=>"Micronésia","es"=>"Micronesia","en"=>"Micronesia"),
    "FO"=>array("pt"=>"Faroé","es"=>"Islas Feroe","en"=>"Faeroe Islands"),
    "FR"=>array("pt"=>"França","es"=>"Francia","en"=>"France"),
    "GA"=>array("pt"=>"Gabão","es"=>"Gabón","en"=>"Gabon"),
    "GB"=>array("pt"=>"Reino Unido","es"=>"Reino Unido","en"=>"United Kingdom"),
    "GD"=>array("pt"=>"Granada","es"=>"Granada","en"=>"Grenada"),
    "GE"=>array("pt"=>"Geórgia","es"=>"Georgia","en"=>"Georgia"),
    "GF"=>array("pt"=>"Guiana Francesa","es"=>"Guayana Francesa","en"=>"French Guiana"),
    "GG"=>array("pt"=>"GUERNSEY","es"=>"GUERNSEY","en"=>"GUERNSEY"),
    "GH"=>array("pt"=>"Gana","es"=>"Ghana","en"=>"Ghana"),
    "GI"=>array("pt"=>"Gibraltar","es"=>"Gibraltar","en"=>"Gibraltar"),
    "GL"=>array("pt"=>"Gronelândia","es"=>"Groenlandia","en"=>"Greenland"),
    "GM"=>array("pt"=>"Gâmbia","es"=>"Gambia","en"=>"The Gambia"),
    "GN"=>array("pt"=>"Guiné","es"=>"Guinea","en"=>"Guinea"),
    "GP"=>array("pt"=>"Guadalupe","es"=>"Guadalupe","en"=>"Guadeloupe"),
    "GQ"=>array("pt"=>"Guiné Equatorial","es"=>"Guinea Ecuatorial","en"=>"Equatorial Guinea"),
    "GR"=>array("pt"=>"Grécia","es"=>"Grecia","en"=>"Greece"),
    "GS"=>array("pt"=>"Geórgia do Sul e Sandwich do Sul","es"=>"Islas Georgia del Sur y Sandwich del Sur","en"=>"South Georgia and the South Sandwich Islands"),
    "GT"=>array("pt"=>"Guatemala","es"=>"Guatemala","en"=>"Guatemala"),
    "GU"=>array("pt"=>"Guame","es"=>"Guam","en"=>"Guam"),
    "GW"=>array("pt"=>"Guiné-Bissau","es"=>"Guinea-Bissau","en"=>"Guinea-Bissau"),
    "GY"=>array("pt"=>"Guiana","es"=>"Guyana","en"=>"Guyana"),
    "HK"=>array("pt"=>"Hong Kong","es"=>"Hong Kong","en"=>"Hong Kong"),
    "HM"=>array("pt"=>"Ilhas Heard e McDonald","es"=>"Islas Heard y McDonald","en"=>"Heard Island and McDonald Islands"),
    "HN"=>array("pt"=>"Honduras","es"=>"Honduras","en"=>"Honduras"),
    "HR"=>array("pt"=>"Croácia","es"=>"Croacia","en"=>"Croatia"),
    "HT"=>array("pt"=>"Haiti","es"=>"Haití","en"=>"Haiti"),
    "HU"=>array("pt"=>"Hungria","es"=>"Hungría","en"=>"Hungary"),
    "ID"=>array("pt"=>"Indonésia","es"=>"Indonesia","en"=>"Indonesia"),
    "IE"=>array("pt"=>"Irlanda","es"=>"Irlanda","en"=>"Ireland"),
    "IL"=>array("pt"=>"Israel","es"=>"Israel","en"=>"Israel"),
    "IM"=>array("pt"=>"ISLE OF MAN","es"=>"ISLE OF MAN","en"=>"ISLE OF MAN"),
    "IN"=>array("pt"=>"Índia","es"=>"India (la)","en"=>"India"),
    "IO"=>array("pt"=>"Território Britânico do Oceano Índico","es"=>"Territorio Británico del Océano Indico","en"=>"British Indian Ocean Territory"),
    "IQ"=>array("pt"=>"Iraque","es"=>"Iraq","en"=>"Iraq"),
    "IR"=>array("pt"=>"Irão","es"=>"Irán","en"=>"Iran"),
    "IS"=>array("pt"=>"Islândia","es"=>"Islandia","en"=>"Iceland"),
    "IT"=>array("pt"=>"Itália","es"=>"Italia","en"=>"Italy"),
    "JE"=>array("pt"=>"JERSEY","es"=>"JERSEY","en"=>"JERSEY"),
    "JM"=>array("pt"=>"Jamaica","es"=>"Jamaica","en"=>"Jamaica"),
    "JO"=>array("pt"=>"Jordânia","es"=>"Jordania","en"=>"Jordan"),
    "JP"=>array("pt"=>"Japão","es"=>"Japón","en"=>"Japan"),
    "KE"=>array("pt"=>"Quénia","es"=>"Kenia","en"=>"Kenya"),
    "KG"=>array("pt"=>"Quirguizistão","es"=>"Kirguizistán","en"=>"Kyrgyzstan"),
    "KH"=>array("pt"=>"Camboja","es"=>"Camboya","en"=>"Cambodia"),
    "KI"=>array("pt"=>"Quiribáti","es"=>"Kiribati","en"=>"Kiribati"),
    "KM"=>array("pt"=>"Comores","es"=>"Comoras","en"=>"Comoros"),
    "KN"=>array("pt"=>"São Cristóvão e Neves","es"=>"San Cristóbal y Nieves","en"=>"Saint Kitts and Nevis"),
    "KP"=>array("pt"=>"Coreia do Norte","es"=>"Corea del Norte","en"=>"North Korea"),
    "KR"=>array("pt"=>"Coreia do Sul","es"=>"Corea del Sur","en"=>"South Korea"),
    "KW"=>array("pt"=>"Kuwait","es"=>"Kuwait","en"=>"Kuwait"),
    "KY"=>array("pt"=>"Ilhas Caimão","es"=>"Islas Caimán","en"=>"Cayman Islands"),
    "KZ"=>array("pt"=>"Cazaquistão","es"=>"Kazajistán","en"=>"Kazakhstan"),
    "LA"=>array("pt"=>"Laos","es"=>"Laos","en"=>"Laos"),
    "LB"=>array("pt"=>"Líbano","es"=>"Líbano","en"=>"Lebanon"),
    "LC"=>array("pt"=>"Santa Lúcia","es"=>"Santa Lucía","en"=>"Saint Lucia"),
    "LI"=>array("pt"=>"Listenstaine","es"=>"Liechtenstein","en"=>"Liechtenstein"),
    "LK"=>array("pt"=>"Sri Lanca","es"=>"Sri Lanka","en"=>"Sri Lanka"),
    "LR"=>array("pt"=>"Libéria","es"=>"Liberia","en"=>"Liberia"),
    "LS"=>array("pt"=>"Lesoto","es"=>"Lesoto","en"=>"Lesotho"),
    "LT"=>array("pt"=>"Lituânia","es"=>"Lituania","en"=>"Lithuania"),
    "LU"=>array("pt"=>"Luxemburgo","es"=>"Luxemburgo","en"=>"Luxembourg"),
    "LV"=>array("pt"=>"Letónia","es"=>"Letonia","en"=>"Latvia"),
    "LY"=>array("pt"=>"Líbia","es"=>"Libia","en"=>"Libya"),
    "MA"=>array("pt"=>"Marrocos","es"=>"Marruecos","en"=>"Morocco"),
    "MC"=>array("pt"=>"Mónaco","es"=>"Mónaco","en"=>"Monaco"),
    "MD"=>array("pt"=>"Moldávia","es"=>"Moldavia","en"=>"Moldova"),
    "ME"=>array("pt"=>"MONTENEGRO","es"=>"MONTENEGRO","en"=>"MONTENEGRO"),
    "MF"=>array("pt"=>"SAINT MARTIN","es"=>"SAINT MARTIN","en"=>"SAINT MARTIN"),
    "MG"=>array("pt"=>"Madagáscar","es"=>"Madagascar","en"=>"Madagascar"),
    "MH"=>array("pt"=>"Ilhas Marshall","es"=>"Islas Marshall","en"=>"Marshall Islands"),
    "MK"=>array("pt"=>"Macedónia","es"=>"Macedonia","en"=>"Former Yugoslav Republic of Macedonia"),
    "ML"=>array("pt"=>"Mali","es"=>"Malí","en"=>"Mali"),
    "MM"=>array("pt"=>"Birmânia","es"=>"Birmania; Myanmar","en"=>"Myanmar"),
    "MN"=>array("pt"=>"Mongólia","es"=>"Mongolia","en"=>"Mongolia"),
    "MO"=>array("pt"=>"Macau","es"=>"Macao","en"=>"Macau"),
    "MP"=>array("pt"=>"Marianas do Norte","es"=>"Islas Marianas del Norte","en"=>"Northern Marianas"),
    "MQ"=>array("pt"=>"Martinica","es"=>"Martinica","en"=>"Martinique"),
    "MR"=>array("pt"=>"Mauritânia","es"=>"Mauritania","en"=>"Mauritania"),
    "MS"=>array("pt"=>"Monserrate","es"=>"Montserrat","en"=>"Montserrat"),
    "MT"=>array("pt"=>"Malta","es"=>"Malta","en"=>"Malta"),
    "MU"=>array("pt"=>"Maurícia","es"=>"Mauricio","en"=>"Mauritius"),
    "MV"=>array("pt"=>"Maldivas","es"=>"Maldivas","en"=>"Maldives"),
    "MW"=>array("pt"=>"Malávi","es"=>"Malaui","en"=>"Malawi"),
    "MX"=>array("pt"=>"México","es"=>"México","en"=>"Mexico"),
    "MY"=>array("pt"=>"Malásia","es"=>"Malasia","en"=>"Malaysia"),
    "MZ"=>array("pt"=>"Moçambique","es"=>"Mozambique","en"=>"Mozambique"),
    "NA"=>array("pt"=>"Namíbia","es"=>"Namibia","en"=>"Namibia"),
    "NC"=>array("pt"=>"Nova Caledónia","es"=>"Nueva Caledonia","en"=>"New Caledonia"),
    "NE"=>array("pt"=>"Níger","es"=>"Níger","en"=>"Niger"),
    "NF"=>array("pt"=>"Ilha Norfolk","es"=>"Isla Norfolk","en"=>"Norfolk Island"),
    "NG"=>array("pt"=>"Nigéria","es"=>"Nigeria","en"=>"Nigeria"),
    "NI"=>array("pt"=>"Nicarágua","es"=>"Nicaragua","en"=>"Nicaragua"),
    "NL"=>array("pt"=>"Países Baixos","es"=>"Países Bajos","en"=>"Netherlands"),
    "NO"=>array("pt"=>"Noruega","es"=>"Noruega","en"=>"Norway"),
    "NP"=>array("pt"=>"Nepal","es"=>"Nepal","en"=>"Nepal"),
    "NR"=>array("pt"=>"Nauru","es"=>"Nauru","en"=>"Nauru"),
    "NU"=>array("pt"=>"Niue","es"=>"Niue","en"=>"Niue"),
    "NZ"=>array("pt"=>"Nova Zelândia","es"=>"Nueva Zelanda","en"=>"New Zealand"),
    "OM"=>array("pt"=>"Omã","es"=>"Omán","en"=>"Oman"),
    "PA"=>array("pt"=>"Panamá","es"=>"Panamá","en"=>"Panama"),
    "PE"=>array("pt"=>"Peru","es"=>"Perú","en"=>"Peru"),
    "PF"=>array("pt"=>"Polinésia Francesa","es"=>"Polinesia Francesa","en"=>"French Polynesia"),
    "PG"=>array("pt"=>"Papua-Nova Guiné","es"=>"Papúa-Nueva Guinea","en"=>"Papua New Guinea"),
    "PH"=>array("pt"=>"Filipinas","es"=>"Filipinas","en"=>"Philippines"),
    "PK"=>array("pt"=>"Paquistão","es"=>"Pakistán","en"=>"Pakistan"),
    "PL"=>array("pt"=>"Polónia","es"=>"Polonia","en"=>"Poland"),
    "PM"=>array("pt"=>"São Pedro e Miquelon","es"=>"San Pedro y Miquelón","en"=>"Saint Pierre and Miquelon"),
    "PN"=>array("pt"=>"Pitcairn","es"=>"Islas Pitcairn","en"=>"Pitcairn Islands"),
    "PR"=>array("pt"=>"Porto Rico","es"=>"Puerto Rico","en"=>"Puerto Rico"),
    "PS"=>array("pt"=>"PALESTINIAN TERRITORY, OCCUPIED","es"=>"PALESTINIAN TERRITORY, OCCUPIED","en"=>"PALESTINIAN TERRITORY, OCCUPIED"),
    "PT"=>array("pt"=>"Portugal","es"=>"Portugal","en"=>"Portugal"),
    "PW"=>array("pt"=>"Palau","es"=>"Palaos","en"=>"Palau"),
    "PY"=>array("pt"=>"Paraguai","es"=>"Paraguay","en"=>"Paraguay"),
    "QA"=>array("pt"=>"Catar","es"=>"Qatar","en"=>"Qatar"),
    "RE"=>array("pt"=>"Reunião","es"=>"Reunión","en"=>"Réunion"),
    "RO"=>array("pt"=>"Roménia","es"=>"Rumania; Rumanía","en"=>"Romania"),
    "RS"=>array("pt"=>"SERBIA","es"=>"SERBIA","en"=>"SERBIA"),
    "RU"=>array("pt"=>"Rússia","es"=>"Rusia","en"=>"Russia"),
    "RW"=>array("pt"=>"Ruanda","es"=>"Ruanda","en"=>"Rwanda"),
    "SA"=>array("pt"=>"Arábia Saudita","es"=>"Arabia Saudí","en"=>"Saudi Arabia"),
    "SB"=>array("pt"=>"Ilhas Salomão","es"=>"Islas Salomón","en"=>"Solomon Islands"),
    "SC"=>array("pt"=>"Seicheles","es"=>"Seychelles","en"=>"Seychelles"),
    "SD"=>array("pt"=>"Sudão","es"=>"Sudán","en"=>"Sudan"),
    "SE"=>array("pt"=>"Suécia","es"=>"Suecia","en"=>"Sweden"),
    "SG"=>array("pt"=>"Singapura","es"=>"Singapur","en"=>"Singapore"),
    "SH"=>array("pt"=>"Santa Helena","es"=>"Santa Helena","en"=>"Saint Helena"),
    "SI"=>array("pt"=>"Eslovénia","es"=>"Eslovenia","en"=>"Slovenia"),
    "SJ"=>array("pt"=>"Svalbard e Jan Mayen","es"=>"Svalbard y Jan Mayen","en"=>"Svalbard and Jan Mayen"),
    "SK"=>array("pt"=>"Eslováquia","es"=>"Eslovaquia","en"=>"Slovakia"),
    "SL"=>array("pt"=>"Serra Leoa","es"=>"Sierra Leona","en"=>"Sierra Leone"),
    "SM"=>array("pt"=>"São Marinho","es"=>"San Marino","en"=>"San Marino"),
    "SN"=>array("pt"=>"Senegal","es"=>"Senegal","en"=>"Senegal"),
    "SO"=>array("pt"=>"Somália","es"=>"Somalia","en"=>"Somalia"),
    "SR"=>array("pt"=>"Suriname","es"=>"Surinam","en"=>"Suriname"),
    "ST"=>array("pt"=>"São Tomé e Príncipe","es"=>"Santo Tomé y Príncipe","en"=>"São Tomé and Príncipe"),
    "SV"=>array("pt"=>"Salvador","es"=>"El Salvador","en"=>"El Salvador"),
    "SY"=>array("pt"=>"Síria","es"=>"Siria","en"=>"Syria"),
    "SZ"=>array("pt"=>"Suazilândia","es"=>"Suazilandia","en"=>"Swaziland"),
    "TC"=>array("pt"=>"Ilhas Turcas e Caicos","es"=>"Islas Turcas y Caicos","en"=>"Turks and Caicos Islands"),
    "TD"=>array("pt"=>"Chade","es"=>"Chad","en"=>"Chad"),
    "TF"=>array("pt"=>"Territórios Austrais Franceses","es"=>"Territorios Australes Franceses","en"=>"French Southern Territories"),
    "TG"=>array("pt"=>"Togo","es"=>"Togo","en"=>"Togo"),
    "TH"=>array("pt"=>"Tailândia","es"=>"Tailandia","en"=>"Thailand"),
    "TJ"=>array("pt"=>"Tajiquistão","es"=>"Tayikistán","en"=>"Tajikistan"),
    "TK"=>array("pt"=>"Tokelau","es"=>"Tokelau","en"=>"Tokelau"),
    "TL"=>array("pt"=>"Timor Leste","es"=>"Timor Oriental","en"=>"East Timor"),
    "TM"=>array("pt"=>"Turquemenistão","es"=>"Turkmenistán","en"=>"Turkmenistan"),
    "TN"=>array("pt"=>"Tunísia","es"=>"Túnez","en"=>"Tunisia"),
    "TO"=>array("pt"=>"Tonga","es"=>"Tonga","en"=>"Tonga"),
    "TR"=>array("pt"=>"Turquia","es"=>"Turquía","en"=>"Turkey"),
    "TT"=>array("pt"=>"Trindade e Tobago","es"=>"Trinidad y Tobago","en"=>"Trinidad and Tobago"),
    "TV"=>array("pt"=>"Tuvalu","es"=>"Tuvalu","en"=>"Tuvalu"),
    "TW"=>array("pt"=>"Taiwan","es"=>"Taiwán","en"=>"Taiwan"),
    "TZ"=>array("pt"=>"Tanzânia","es"=>"Tanzania","en"=>"Tanzania"),
    "UA"=>array("pt"=>"Ucrânia","es"=>"Ucrania","en"=>"Ukraine"),
    "UG"=>array("pt"=>"Uganda","es"=>"Uganda","en"=>"Uganda"),
    "UM"=>array("pt"=>"Ilhas Menores Distantes dos Estados Unidos","es"=>"Islas menores alejadas de los Estados Unidos","en"=>"United States Minor Outlying Islands"),
    "US"=>array("pt"=>"Estados Unidos","es"=>"Estados Unidos","en"=>"United States"),
    "UY"=>array("pt"=>"Uruguai","es"=>"Uruguay","en"=>"Uruguay"),
    "UZ"=>array("pt"=>"Usbequistão","es"=>"Uzbekistán","en"=>"Uzbekistan"),
    "VA"=>array("pt"=>"Vaticano","es"=>"El Vaticano","en"=>"Vatican City"),
    "VC"=>array("pt"=>"São Vicente e Granadinas","es"=>"San Vicente y las Granadinas","en"=>"Saint Vincent and the Grenadines"),
    "VE"=>array("pt"=>"Venezuela","es"=>"Venezuela","en"=>"Venezuela"),
    "VG"=>array("pt"=>"Ilhas Virgens Britânicas","es"=>"Islas Vírgenes Británicas","en"=>"British Virgin Islands"),
    "VI"=>array("pt"=>"Ilhas Virgens Americanas","es"=>"Islas Vírgenes Americanas","en"=>"US Virgin Islands"),
    "VN"=>array("pt"=>"Vietname","es"=>"Vietnam","en"=>"Vietnam"),
    "VU"=>array("pt"=>"Vanuatu","es"=>"Vanuatu","en"=>"Vanuatu"),
    "WF"=>array("pt"=>"Wallis e Futuna","es"=>"Wallis y Futuna","en"=>"Wallis and Futuna"),
    "WS"=>array("pt"=>"Samoa","es"=>"Samoa","en"=>"Samoa"),
    "YE"=>array("pt"=>"Iémen","es"=>"Yemen","en"=>"Yemen"),
    "YT"=>array("pt"=>"Mayotte","es"=>"Mayotte","en"=>"Mayotte"),
    "ZA"=>array("pt"=>"África do Sul","es"=>"Sudáfrica","en"=>"South Africa"),
    "ZM"=>array("pt"=>"Zâmbia","es"=>"Zambia","en"=>"Zambia"),
    "ZW"=>array("pt"=>"Zimbabué","es"=>"Zimbabue","en"=>"Zimbabwe")
);
?>